name: sagar's build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/dev
      - name: install
        run: |
          npm install cypress
      - name: uat
        run: |
          npx cypress run --spec "cypress/integration/examples/test.spec.js"
