name: christianfei-devblog build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@dev
        with:
          ref: refs/heads/dev
      - name: install
        run: |
          npm cypress install
      - name: uat
        run: |
          npx run cypress
